#ifndef C4D_SYMBOLS_H
#define C4D_SYMBOLS_H

enum {
    IDS_TOOLPRESETS,
    IDS_TOOLPRESETS_HELP,
    IDS_MISSING_FILE,
    IDS_PRESET,
    IDC_FOLDER,
    IDC_TOOLNOTSUPPORTED,
    IDC_UNKOWNTOOL,
    IDS_ERROR_FILENOTOPENED,
    IDS_ERROR_ACCESSDENIED,
    IDS_ERROR_NAMEEMPTY,
    IDC_ERROR_RENAMEFAILED,
    IDC_ERROR_FOLDERCREATIONFAILED,
    IDC_ERROR_FOLDEREXISTS,
    IDC_ERROR_PRESETSNOTREMOVED,
    IDC_ASK_REMOVEALL,
    IDC_ASK_REMOVENODE,
    IDC_ASK_REMOVENODE_MULTIPLE,

    MENU_FILE,
    MENU_FILE_SETTINGS,

    CONTEXT_NEWFOLDER,
    CONTEXT_OPEN,

    TREEVIEW,
    COLUMN_MAIN,
    BMPB_SAVE,
    BMPB_RELOAD,
    STR_TOOL,
    BMPB_TOOL,
    GRP_MAIN,
    GRP_TOOL,
    CHK_ALL,
};

#endif
